import Head from "next/head";
import { Inter } from "next/font/google";
import { Box } from "@chakra-ui/react";
import {
  Navbar,
  HeroSection,
  BestSellingBooks,
  Footer,
  BestBook,
} from "@/components/molecules";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pathok Point</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box width="100%">
        <Navbar></Navbar>
        <Box margin={{base:"0px", md:"0 20px"}}>
          <HeroSection />
        </Box>
        <BestSellingBooks></BestSellingBooks>
        <BestBook></BestBook>
        <Footer></Footer>
      </Box>
    </>
  );
}
