import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import { PathokButton } from "@/components/atoms";

import { Box, Text } from "@chakra-ui/react";
import { Navbar } from "@/components/molecules";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pathok Point</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar></Navbar>
      </div>

      {/* <nav>
        <Box height={157} width="100%" bgColor="#002E38">
          <PathokButton text="Button" />
          <Text
            color="#fff"
            textAlign="center"
            fontSize={["10px", "50px", "100px"]}
          ></Text>
        </Box>
        <Image
          width={100}
          height={100}
          src="/images/bkash-logo-dark.90c635aa.png"
          alt="demo"
        />
      </nav> */}
    </>
  );
}
